"""Added Encouter Procedure Observation

Revision ID: 9469e3feb34b
Revises: 5c0930839088
Create Date: 2019-11-28 10:46:40.981553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9469e3feb34b'
down_revision = '5c0930839088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encouters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('type_code', sa.String(), nullable=True),
    sa.Column('type_code_system', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('encouter_id', sa.Integer(), nullable=True),
    sa.Column('observation_date', sa.Date(), nullable=True),
    sa.Column('type_code', sa.String(), nullable=True),
    sa.Column('type_code_system', sa.String(), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('unit_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['encouter_id'], ['encouters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('encouter_id', sa.Integer(), nullable=True),
    sa.Column('procedure_date', sa.Date(), nullable=True),
    sa.Column('type_code', sa.String(), nullable=True),
    sa.Column('type_code_system', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['encouter_id'], ['encouters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('procedures')
    op.drop_table('observations')
    op.drop_table('encouters')
    # ### end Alembic commands ###
