"""postgersql init 2

Revision ID: ad6f75e63e64
Revises: 
Create Date: 2019-12-02 13:46:09.369573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6f75e63e64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('race_code', sa.String(), nullable=True),
    sa.Column('race_code_system', sa.String(), nullable=True),
    sa.Column('ethnicity_code', sa.String(), nullable=True),
    sa.Column('ethnicity_code_system', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encouters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('type_code', sa.String(), nullable=True),
    sa.Column('type_code_system', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('encouter_id', sa.Integer(), nullable=True),
    sa.Column('observation_date', sa.Date(), nullable=True),
    sa.Column('type_code', sa.String(), nullable=True),
    sa.Column('type_code_system', sa.String(), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('unit_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['encouter_id'], ['encouters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('encouter_id', sa.Integer(), nullable=True),
    sa.Column('procedure_date', sa.Date(), nullable=True),
    sa.Column('type_code', sa.String(), nullable=True),
    sa.Column('type_code_system', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['encouter_id'], ['encouters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('procedures')
    op.drop_table('observations')
    op.drop_table('encouters')
    op.drop_table('patients')
    # ### end Alembic commands ###
